### PR TITLE
Conditionally compile atomic implementations

### PR DESCRIPTION
**Pull request by fwcd**
This enables compilation e.g. on 32-bit platforms where 64-bit atomics may be unavailable.

### CODE REVIEW

**Comment by udoprog** [comment]
Hi!

Since it's using `cfg_target_has_atomic`, it makes musli nightly only. I think the only option is to put it behind a feature flag the user is responsible for turning off. Unless there's some other way to make it work on stable.

**Comment by fwcd** [comment]
I've updated it to use feature flags. Once https://github.com/rust-lang/rust/issues/94039 stabilizes, we could deprecate the features and revert to the original implementation (a96056c).

**Comment by fwcd** [comment]
Any update on this?

**Comment by udoprog** [comment]
Looks Ok, I've been working on some other things and haven't come back to this project yet. But I'll rebase this for now.

I might tweak the features before release, but I haven't decided how yet.

**Comment by udoprog** [comment]
@fwcd So I was looking around how other projects was approaching this, and `target_has_atomic` is stable since `1.60`. So what I did in the last PR was to try and lean on that instead. While the visibility of `Atomic*` depends on `target_has_atomic_load_store` (which is nightly only) it seems like there's no reasonable case where the two would diverge.

Could you take the commit I pushed for a spin in your project and see if it works as expected?

**Pull request closed without merging**
